apiVersion: v2
name: task-minio-chart
description: A custom Helm chart for MinIO, depending on the Bitnami chart.
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: minio
    version: "17.0.9"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.enabled
